export const data = [
  {
    name: "Delicious Delights",
    rating: 4.5,
    cuisines: ["Italian", "Mediterranean"],
    image: "https://example.com/delicious-delights.jpg",
    id: 8924,
  },
  {
    name: "Sizzling Sushi House",
    rating: 4.2,
    cuisines: ["Japanese", "Sushi"],
    image: "https://example.com/sizzling-sushi-house.jpg",
    id: 4524,
  },
  {
    name: "Burger Barn",
    rating: 4.0,
    cuisines: ["American", "Burgers"],
    image: "https://example.com/burger-barn.jpg",
    id: 1224,
  },
  {
    name: "Spice Palace",
    rating: 4.4,
    cuisines: ["Indian", "Spicy"],
    image: "https://example.com/spice-palace.jpg",
    id: 924,
  },
  {
    name: "Seafood Haven",
    rating: 4.7,
    cuisines: ["Seafood", "Cajun"],
    image: "https://example.com/seafood-haven.jpg",
    id: 314,
  },
  {
    name: "Mama Mia Pizzeria",
    rating: 4.3,
    cuisines: ["Italian", "Pizza"],
    image: "https://example.com/mama-mia-pizzeria.jpg",
    id: 3242,
  },
  {
    name: "Taco Town",
    rating: 4.1,
    cuisines: ["Mexican", "Tacos"],
    image: "https://example.com/taco-town.jpg",
    id: 3248,
  },
  {
    name: "Green Garden",
    rating: 4.6,
    cuisines: ["Vegetarian", "Healthy"],
    image: "https://example.com/green-garden.jpg",
    id: 334,
  },
  {
    name: "Sizzlin Steaks",
    rating: 4.8,
    cuisines: ["Steakhouse", "Grill"],
    image: "https://example.com/sizzlin-steaks.jpg",
    id: 34,
  },
  {
    name: "Noodle Nirvana",
    rating: 4.4,
    cuisines: ["Asian", "Noodles"],
    image: "https://example.com/noodle-nirvana.jpg",
    id: 32,
  },
  {
    name: "The Breakfast Club",
    rating: 4.0,
    cuisines: ["Breakfast", "Brunch"],
    image: "https://example.com/the-breakfast-club.jpg",
    id: 324,
  },
  {
    name: "Pasta Paradise",
    rating: 4.3,
    cuisines: ["Italian", "Pasta"],
    image: "https://example.com/pasta-paradise.jpg",
    id: 3294,
  },
];
